#!/usr/bin/env python3
"""Write build_version.h with the PulseNest and incunest_afe4490 git hashes (ESP-IDF build).

Usage: gen_build_version.py <pulsenest_dir> <library_dir> <output.h>

Same rule as the PlatformIO-era scripts/pre_build_hash.py: short hash of HEAD, with "-dirty"
appended when the working tree has local changes (tracked files only), "unknown" when the
directory is not a git repository. Two repositories, two hashes: a change in main.cpp does not
move the library's hash and vice versa, so one alone cannot identify the firmware that produced a
capture. The header is rewritten only when its content changes, so an unchanged tree does not
recompile main on every `idf.py build`.
"""
import os
import subprocess
import sys


def _git(args, cwd):
    try:
        r = subprocess.run(["git"] + args, cwd=cwd, capture_output=True, text=True, timeout=5)
    except Exception:
        return None
    return r.stdout.strip() if r.returncode == 0 else None


def describe(path):
    if not path or not os.path.isdir(path):
        return "unknown"
    h = _git(["rev-parse", "--short", "HEAD"], path)
    if not h:
        return "unknown"
    if _git(["status", "--porcelain", "--untracked-files=no"], path):
        h += "-dirty"
    return h


def main():
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    pulsenest_dir, lib_dir, out = sys.argv[1], sys.argv[2], sys.argv[3]
    pn, lib = describe(pulsenest_dir), describe(lib_dir)
    content = (
        "// Generated by scripts/gen_build_version.py on every build — do not edit, do not commit.\n"
        f'#define PULSENEST_GIT_HASH "{pn}"\n'
        f'#define INCUNEST_GIT_HASH  "{lib}"\n'
    )
    try:
        with open(out, encoding="utf-8") as f:
            if f.read() == content:
                return 0
    except OSError:
        pass
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print(f"build_version.h: PulseNest {pn}, incunest_afe4490 {lib}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
