"""Selecting captures without hardcoding filenames.

The experiment scripts used to carry their own list of capture paths — the same four
duplicated across hr1_detector_experiment.py and hr1_filter_experiment.py, so adding a
capture meant editing two files. Worse, those paths carried subject names and ages into a
public repository.

Both problems have the same fix: ask the manifest for captures matching a CRITERION, and
let the manifest decide which files that is. See captures/CAPTURE_SET_SPEC.md §2.5 for why
the manifest is two files:

    captures/index.csv   derived, regenerated by build_capture_index.py, never hand-edited
    captures/truth.csv   authored, holds tier/condition/ground truth

Typical use:

    from capture_set import select
    for cap in select(tier="T1", condition="R2"):
        run(cap.path)
"""
import csv
import io
import os

CAPTURES_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "captures")
INDEX_PATH = os.path.join(CAPTURES_DIR, "index.csv")
TRUTH_PATH = os.path.join(CAPTURES_DIR, "truth.csv")


class Capture(object):
    """One capture: its path plus the merged index (derived) and truth (authored) rows."""

    def __init__(self, name, index_row, truth_row):
        self.name = name
        self.path = os.path.join(CAPTURES_DIR, name)
        self.index = index_row or {}
        self.truth = truth_row or {}

    def __repr__(self):
        return "<Capture %s tier=%s cond=%s>" % (
            self.name, self.truth.get("tier") or "?", self.truth.get("condition") or "?")

    # Convenience accessors for the fields callers actually reach for.
    @property
    def tier(self):
        return self.truth.get("tier") or ""

    @property
    def condition(self):
        return self.truth.get("condition") or ""

    @property
    def duration_s(self):
        try:
            return float(self.index.get("duration_s") or 0)
        except ValueError:
            return 0.0

    @property
    def truth_hr_bpm(self):
        """Ground-truth rate. A plain number for a steady capture; the raw string for a
        segmented one ([[t0,t1,v],...]), which the caller must parse knowingly."""
        raw = (self.truth.get("truth_hr_bpm") or "").strip()
        if not raw:
            return None
        try:
            return float(raw)
        except ValueError:
            return raw

    @property
    def has_config(self):
        return self.index.get("has_config_header") == "yes"


def _read(path):
    if not os.path.exists(path):
        return {}
    with io.open(path, encoding="utf-8", newline="") as fh:
        return {r["file"]: r for r in csv.DictReader(fh)}


def load_all():
    """Every capture the manifest knows about, index and truth merged."""
    index, truth = _read(INDEX_PATH), _read(TRUTH_PATH)
    names = sorted(set(index) | set(truth))
    if not names:
        raise RuntimeError(
            "No capture manifest. Run:  python tools/build_capture_index.py")
    return [Capture(n, index.get(n), truth.get(n)) for n in names]


def select(tier=None, condition=None, min_duration_s=None, requires_config=False,
           names=None):
    """Captures matching every criterion given. Unset criteria do not filter.

    tier / condition accept a string or a collection of strings.
    names is an escape hatch for a fixed set — it still goes through the manifest, so a
    typo raises instead of silently yielding nothing.
    """
    caps = load_all()

    if names is not None:
        wanted = [names] if isinstance(names, str) else list(names)
        known = {c.name: c for c in caps}
        missing = [n for n in wanted if n not in known]
        if missing:
            raise KeyError("Not in the manifest: %s (regenerate the index?)" % ", ".join(missing))
        caps = [known[n] for n in wanted]

    def matches(value, criterion):
        if criterion is None:
            return True
        if isinstance(criterion, str):
            return value == criterion
        return value in criterion

    out = []
    for c in caps:
        if not matches(c.tier, tier):
            continue
        if not matches(c.condition, condition):
            continue
        if min_duration_s is not None and c.duration_s < min_duration_s:
            continue
        if requires_config and not c.has_config:
            continue
        if not os.path.exists(c.path):
            continue          # listed in the manifest but not on this machine
        out.append(c)
    return out


# The working set for the HR1 filter/detector experiments, in ONE place instead of copied
# into each script. Two simulator captures with known truth (60 BPM) plus subject captures
# for real waveform morphology, which no simulator reproduces.
#
# Still a fixed list rather than a criterion query because truth.csv has not been annotated
# yet — once tier/condition are filled in, this becomes
#     select(tier="T1", condition="I1") + select(tier="T3")
# and the names disappear from the source entirely.
HR1_EXPERIMENT_SET = [
    "PHOTOTHERAPY_500HZ_SIMUL_60BPM_96SPO2_20260624_083336.csv",
    "PHOTOTHERAPY_ONOFF_60BPM_90SPO2_20260618_180045.csv",
    "PHOTOTHERAPY_400HZ_SIMUL_60BPM_96SPO2_20260624_083632.csv",
    "SUBJ01_A57_RF100K_20260823_184201.csv",
    "SUBJ01_A57_RF250k_20260823_184045.csv",
    "SUBJ04_A19_AL_REVES_20260823_180835.csv",
    "SUBJ06_A15_20260823_175947.csv",
]


def hr1_experiment_captures():
    """Paths for HR1_EXPERIMENT_SET, skipping any missing from this machine."""
    known = {c.name for c in load_all()}
    return [os.path.join(CAPTURES_DIR, n) for n in HR1_EXPERIMENT_SET
            if n in known and os.path.exists(os.path.join(CAPTURES_DIR, n))]


if __name__ == "__main__":
    caps = load_all()
    print("%d captures in the manifest" % len(caps))
    annotated = [c for c in caps if c.tier]
    print("%d with a tier, %d without" % (len(annotated), len(caps) - len(annotated)))
    print("\nHR1 experiment set:")
    for p in hr1_experiment_captures():
        print("   " + os.path.basename(p))
